### ISSUE TITLE
Ginger?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#10]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/GingerPlant.JPG/450px-GingerPlant.JPG)

**Comment by westnordost** [comment]
I'd say no. Is it perennial though? Because even if it does not look like bushes from satellite, if it is rightfully tagged as orchard (=perennial fruits(?)), then it should be included.

**Comment by rugk** [comment]
* [x] is perennial/always grown in monoculture
* [ ] is grown on orchards/satellite images can be confused with orchards

**Comment by rugk** [comment]
http://www.jungle-power.net/Ingwer:_:1321.html

>  Das ätherische Öl, das man in Deutschland erhält, stammt meist aus Indien oder Madagaskar. Wilder Ingwer ist heute nicht mehr zu finden, es gibt ihn nur noch im kultivierten Anbau. Es handelt sich hierbei um eine aufrechte, mehrjährige Pflanze von bis zu einem Meter Höhe mit dickem, wucherigem Wurzelstock. Dieser ist von beißendem Geruch. Jedes Jahr wächst aus dieser mehrjährigen Wurzel ein grüner, schilfrohrähnlicher Scheinstengel von ca. ein bis zwei Metern Höhe.[…]Jüngere Knollen sind zarter im Geschmack, zum Beispiel die auch als Stern Ingwer bekannten einjährig geernteten Rhizome, aus denen eingelegter Ingwer gemacht wird.

**Comment by westnordost** [comment]
Still, judging by the images, I'd say no. I mean, ginger is the root of this plant. The whole plant (like potatoes, onions,...) must be harvested.

**Comment by rugk** [comment]
For an orchard? No, your definition [was](https://github.com/rugk/crops-parser/issues/14#issuecomment-312864285) that only parts of the plants must be harvested.

Potatoes and onions are good examples of plantations, not orchards. That's the whole point, we discuss about here. :smile: 

 But roots are really a good arguments against ginger. It's like potatoes, although the plant is taller. And I just hope it won't be confused with orchards. So, exclude?

**Comment by westnordost** [comment]
Potatoes and onions are a plantation for you? Why?

The whole plant is harvested of course, how else would you get the roots? You can't remove the root and then stick it back into the earth. Cereals are also harvested as a whole even though it is mainly only to get the seed.

The point is with "harvesting whole" is that the field is empty after that. Anything else could be planted thereafter.
Here, have a video:
https://www.youtube.com/watch?v=OqYCn_qsLj0

**Comment by rugk** [comment]
Hmm, good question. I see that "orchard" is often translated as "Obstgarten" and includes fruits you pick up. And potatoes are not part of it, they only grow on the ground, are neither "trees or shrubs" (Wikipedia def. of orchards). So I'd say they are grown on orchards.

Also compare [:potato: orchards](https://duckduckgo.com/?q=Potatoes+orchards&iax=1&ia=images) vs [plantations](https://duckduckgo.com/?q=Potatoes+plantations&iar=images&iax=1&ia=images). The second image search yields way more "correct"/useful responses, i.e. fields and not single fruits.

But if you want to discuss that 8they are currently excluded) better do that in a new issue.

BTW I have no idea why the English [article on orchards](https://en.wikipedia.org/wiki/Orchard) seriously links to the German article "Streuobstwiese"…

**Comment by westnordost** [comment]
Yes it is good they are excluded.

**Comment by rugk** [comment]
But they are still no orchards…

So anyway, back to ginger. My last point was:
> But roots are really a good arguments against ginger. It's like potatoes, although the plant is taller. And I just hope it won't be confused with orchards. So, exclude?

**Comment by westnordost** [comment]
There was a misunderstanding here. I used "plantation" as a synonym for "orchard". 

"Exclude" means "not an orchard", right?

**Comment by rugk** [comment]
> I used "plantation" as a synonym for "orchard".

thing is, they are different. That's the whole point here. (Or, at least, an orchard is a type of plantation, but not vice versa.)

That's why I explicitly said:
> Potatoes and onions are good examples of plantations, **not orchards**.

> "Exclude" means "not an orchard", right?

Right.

**Comment by rugk** [comment]
So I am excluding this now.
