### ISSUE TITLE
Artichokes?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#11]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Pleubian_22_Artichauts_2010.jpg/640px-Pleubian_22_Artichauts_2010.jpg)

**Comment by westnordost** [comment]
No idea

**Comment by rugk** [comment]
But you would agree as for the satellite thing?
* [ ] is perennial/always grown in monoculture
* [ ] is grown on orchards/satellite images can be confused with orchards

**Comment by westnordost** [comment]
For that one image you posted here, I would say no. From above, it looks like normal farmland.
These look more like plantation: [1](http://2.bp.blogspot.com/_tOCJq_OzyI8/SF_2Hv4OSjI/AAAAAAAAACg/EQQOJaSsYBM/s400/OilPalmPlantation3_small.jpg) [2](http://theartichokeblog.com/wp-content/uploads/2009/12/plantation.jpg)
But this definitely not: [1](http://l7.alamy.com/zooms/3db9e382566e4d13aeebb2521ef98f6e/man-working-on-the-artichoke-plantation-with-a-tractor-at-sunset-h7hk9n.jpg) (You don't plow through a orchard with a tractor I'd think)

**Comment by rugk** [comment]
Okay, so I'd choose, exclude.

Farmland != orchard…

**Comment by westnordost** [comment]
Yes
