### ISSUE TITLE
Sisal?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#12]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sisal_Fields_in_Northern_Tanzania.jpg/640px-Sisal_Fields_in_Northern_Tanzania.jpg)

**Comment by westnordost** [comment]
Couldn't find any information whether it is cultivated perennial, but the plant itself is. I have also seen a lot of images with rather big sisal plants, so my guess is that they are.

**Comment by rugk** [comment]
* [x] is perennial/always grown in monoculture
* [x] is grown on orchards/satellite images can be confused with orchards

So, include.

**Comment by rugk** [comment]
done in next commit
