### ISSUE TITLE
Vanilla?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#13]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/8/82/Vanilla_fragrans_3.jpg)

**Comment by westnordost** [comment]
Looks like it.

**Comment by rugk** [comment]
* [x] is perennial/always grown in monoculture ([source](https://de.wikipedia.org/wiki/Vanille_(Orchideen)))
* [x] is grown on orchards/satellite images can be confused with orchards

Okay, so include.

**Comment by rugk** [comment]
done in next commit
