### ISSUE TITLE
Hemp?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#14]
In some countries they are legal, as it seems.

Affects Hemp tow waste and Hempseed

**Comment by westnordost** [comment]
Why would it? There are cultivars which are not usable for THC production: https://de.wikipedia.org/wiki/Nutzhanf

The hemp (for hemp fibre) is being collected with trucks on farmland.

**Comment by rugk** [comment]
Questions are these:
* [x] is perennial/always grown in monoculture (???)
* [x] is grown on orchards/satellite images can be confused with orchards

**Comment by westnordost** [comment]
For fibre, the whole plants are harvested, there is nothing left.

**Comment by rugk** [comment]
Well… they can always grow the hemp on the same field again. That's the question…
Or is that too unlikely? Does hemp need drop rotation? 

Ah, just found something:
> Since hemp is very self-compatible, it can also be grown several years in a row in the same fields (monoculture).

https://en.wikipedia.org/wiki/Hemp

So, we include it?

**Comment by westnordost** [comment]
Nothing needs crop rotation if you have fertilizer. That is not my point, my point is that the whole plant is harvested (with a tractor) and for me this makes a distinction between orchard and farmland. Tractors don't plow through coffee plantations, apple tree plantations, wine plantations etc., the fruits needs to be picked. For hemp, the whole plant is harvested (at least for fibre production), just like it is done for cereals, rice, sugar canes etc.

**Comment by rugk** [comment]
Okay, yeah. Then maybe we need to retag this to `landuse=farmland`, that's okay. But from satellite images it certainly can look like an orchard. That's the reason to include them.

**Comment by westnordost** [comment]
[Really?](http://il2.picdn.net/shutterstock/videos/7979482/thumb/1.jpg)

https://www.shutterstock.com/video/clip-7979470-stock-footage-cannabis-marijuana-plantation-cannabis-marijuana-weed-plantation-aerial-fly-over-shoot-in-slovenia.html

This does not look at all like a plantation, in my opinion. The hemp plants are harvested young I think, so they don't get that big as they could (like with cotton).

**Comment by rugk** [comment]
Well… we also included [Sisal](https://github.com/rugk/crops-parser/issues/12) (and we excluded [cotton](https://github.com/rugk/crops-parser/issues/9) BTW.) and [coffee](https://coffeetruth.files.wordpress.com/2011/01/segafredo-plantation.jpg) does look not that different IMHO. Both "plantationy", as you expressed it.

**Comment by westnordost** [comment]
We could also exclude sisal, really. It is the same thing as with hemp. They are both harvested fully for their fiber.

For the coffee pic: Really? In plantations where people pick the fruits, you always have these walkways. The video I linked does not have these walkways at all. (The distance between each row is something you see for every crop planted with a tractor, cereals, maize etc.)

**Comment by westnordost** [comment]
https://www.youtube.com/watch?v=GaGcrh0o4JA

**Comment by rugk** [comment]
Okay, okay, you've convinced me. It's like cereals (only a bit more green from satellite). It's clear that this is no orchard, but would need retagging and it should not be confused. So, exclude.
