### ISSUE TITLE
Final review of OSM tag list

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#15]
@westnordost

When all other issues here are closed, please have a final look at the [crop OSM list](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv). Look for crops, which may not fit the criteria of perennial/monoculture and are either planted in orchards or can be confused with orchards from satellite images. Maybe also have a look at the new OSM tags.
It's also a good idea to check all crops we removed/excluded from the data. Just have a look over them.

Steps:
* [x] Close [all other issues](https://github.com/rugk/crops-parser/issues?utf8=%E2%9C%93&q=is%3Aissue%20no%3Alabel%20is%3Aopen%20) regarding inclusion/exclusions of crops.
* [x] @rugk: Regenerate another list with all blacklisted crops
* [x] @westnordost: Review [OSM "whitelist"](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv). Any crop is listed here.
* [x] @westnordost: Review the regenerated [removed crops](https://github.com/rugk/crops-parser/blob/master/result/missingOSM.list) list. Did I/we remove some, which may be included?
* [x] Possibly apply changes.
* [x] Let unofficial OSM tags to be approved/suggest them/just add them to the wiki page
* [x] Possibly apply changes to OSM tags.
* [x] Regenerate top-5 list.

Afterwards we should have data we can work with and can continue with https://github.com/westnordost/StreetComplete/issues/368.

**Comment by rugk** [comment]
I've regenerated the lists. We are mostly only interested in the OSMonly version, [2013/14 here](https://github.com/rugk/crops-parser/blob/master/result/mostPlantedCrops_2014%2B2013_OSMonly.yml) and [only 2014 here](https://github.com/rugk/crops-parser/blob/master/result/mostPlantedCrops_2014_OSMonly.yml).

So, @westnordost, you can start reviewing. If we miss something that's not too bad, as we can always adjust the white/blacklists and regenerate the data (and anyone to report a missing crop, can just be directed here to open an issue or see the previous discussion if we already covered it), but in the end, you'll take responsibility for a good selection of top-crops per country in your app. :wink:

**Comment by westnordost** [comment]
Looks good, as far as I can tell. The question is: What to do with this data now. Will it be the order in which the plants are shown (as in the sports quest) or will it be the "complete" list of each all the plants that are shown for the given country? I think the latter will not make so much sense, but for the former, we need a definite list of plants that should be shown in total. How many crops in total are they?

**Comment by westnordost** [comment]
Do you have a list of all crops there are?

**Comment by rugk** [comment]
> Looks good, as far as I can tell. 

Did you had a look at both the blacklist and the whitelist? (see first post)
So can I tick both points?

>  Will it be the order in which the plants are shown (as in the sports quest)

Yes, I'd say so. 

> Do you have a list of all crops there are?

Sure – if you only care for OSM tags –, just take the [list of OSM tags](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv). As said, some are doubled and the lines with `??????` also have to be ignored.

In any case we cannot show all crops.

**Comment by westnordost** [comment]
> Did you had a look at both the blacklist and the whitelist? (see first post)

You forgot to remove potatoes from the whitelist. Also, yes, it should be trees=palms. Additionally, it should be trees=blueberry_plants, same for the other berries.
How come grapefruit is on the blacklist?

> In any case we cannot show all crops.

Yes. Well, I see two possibilities.
- sort the different trees by climate zone and then only show these per country. Requires to note down the climate zones in each country 
- or, instead of top 5 or so, have an **exhaustive** list of crops that are planted in each country (sorted by importance). But, can you even generate such a list?

Additionally, all those nuts could be put together into one answer choice - the user can simply answer to the question what is being cultivated here: "nuts". And then, mayybee later a quest where he specifies which nuts. Perhaps same for berries.

**Comment by rugk** [comment]
> You forgot to remove potatoes from the whitelist.

Ouch, now I know this review was a good idea… :smile: 

> Also, yes, it should be trees=palms.

Right.

> Additionally, it should be trees=blueberry_plants, same for the other berries.

Actually the way without "plants" is the official one [documented in the wiki](https://wiki.openstreetmap.org/wiki/Key:trees#Tagging). Don't ask me why…

> How come grapefruit is on the blacklist?

I have no idea. Thanks for spotting. I'll add it.

> sort the different trees by climate zone and then only show these per country. Requires to note down the climate zones in each country

You know I don't like that climate zone thing as we have no data for it.

> or, instead of top 5 or so, have an exhaustive list of crops that are planted in each country (sorted by importance). But, can you even generate such a list?

Well… just the top-20 or top-∞ out of this data. I already showed it to you and you said, "soo much data"… :smiley: 
And as you always say, if a crop is really missing, the user should/has to create a note anyway.

In the end, I would like to have a selection similar to the sports quests, but maybe when you tap on "more" the input changes to the the "search to type" input we discussed earlier. This would allow the user to select from the comprehensive list and we only need a top-5 per country.

**Comment by westnordost** [comment]
> Actually the way without "plants" is the official one documented in the wiki. Don't ask me why…

Yeah whoever documented that, didn't think. It is simply inconsistent to the rest. Look at the usage of the tag, you will see that there is still a lot of leeway here, most values are everything else than established.

>You know I don't like that climate zone thing as we have no data for it.

"Rough" climate zones (tropical, subtropical, temperate, cold) of the earth on a country-map: https://de.wikipedia.org/wiki/Klimazone#/media/File:Klimag%C3%BCrtel-der-erde.svg
Where plants grow can usually be found on the wikipedia.

But okay, if we have the data, I also find the "exhaustive list" approach better.

Okay, compromise. Let's start with a top-15 list for now (3x5 tiles in a photo-image list). The "search to type" component is something I would need to implement first, I'd like to postpone that to later. Basically, the sports quest could also be improved with this component.

**Comment by rugk** [comment]
> Where plants grow can usually be found on the wikipedia.

Yeah, but this only includes the natural/native origin of the plant, not (necessarily) where it is planted for harvesting.

> Okay, compromise. Let's start with a top-15 list for now (3x5 tiles in a photo-image list).

Okay, good. let's finish this issue first, however.

So we need to add them to the wiki or so. Is there any "official" way we can/should go to approve these  tags or should I just edit the wiki?

**Comment by westnordost** [comment]
Never really edited the wiki. I guess it cannot be wrong to first publish the complete list in the discussion section, saying that it will soon be implemented this way in Streetcomplete. Then later if noone objects it can be put into the main page.

**Comment by rugk** [comment]
Done: 
* https://wiki.openstreetmap.org/wiki/Talk:Key:trees#Adding_trees_keys
* https://wiki.openstreetmap.org/wiki/Talk:Key:crop#Adding_crop_keys

**Comment by rugk** [comment]
I've added the keys to the wiki, so we can close this issue. The list is a top-15 list too now and I regenerated it some time ago. There were no changes until now, so we can close this issue.
