### ISSUE TITLE
Seed cotton, sugar cane and other farmland products

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#2]
@westnordost

"Seed cotton", "Cotton lint" and "Cottonseed" are all crops in the source data. Now, cotton is perennial, but usually cultivated only for one year (acc. to Wikipedia). So what to do about this? Blacklist it?

**Comment by westnordost** [comment]
I don't think so, see "Anbaubedingungen". But I guess, is it tagged under orchard or farmland?

On 2 July 2017 10:46:59 CEST, rugk <notifications@github.com> wrote:
>@westnordost
>
>"Seed cotton", "Cotton lint" and "Cottonseed" are all crops in the
>source data. Now, cotton is perennial, but usually cultivated only for
>one year (acc. to Wikipedia). So what to do about this? Blacklist it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crop-parser/issues/2

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> I don't think so, see "Anbaubedingungen".

Ah, right. It seems to always stay there.

It is/should be tagged under farmland as it seems:
> * plantings of non-tree crops (typically based on historic use of the word 'plantation'), such as for sugar cane, tobacco, cotton. These crops are not permanent. Use landuse=farmland

https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dplantation

And "sugar cane" is also quite popular worldwide (actually 79x in the top 5) and also worldwide the most planted thing. Maybe we also have to include farmland sometimes.
At least it should be possible [to recognize it](https://commons.wikimedia.org/wiki/File:Saccharum-officinarum-harvest.JPG) and it is also cultivated for more than one year:
> Sugarcane is cultivated […] for a continuous period of more than 6-7 months each year.[…] In countries with a more traditional type of agriculture with smaller fields and hand harvesting […] sugar canes are often harvested up to 10 years before replanting.

https://en.wikipedia.org/wiki/Sugarcane

**Comment by westnordost** [comment]
Interesting. Well, the "plantation" quest could simply include cotton, sugarcane etc. but then internally if the user answered i.e. "sugarcane" retag it to `landuse=farmland+produce=sugarcane` (or whatever is the correct tag for that)

**Comment by rugk** [comment]
Okay, this sounds good, so I leave them in the dataset.
