### ISSUE TITLE
Does it need to be a photo?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#21]
Or would https://de.wikipedia.org/wiki/Paprika#/media/File:Illustration_Capsicum_annuum0.jpg when cut to the left-bottom corner also work?

Or this one for [oranges](https://de.wikipedia.org/wiki/Datei:Histoire_et_culture_des_orangers_A._Risso_et_A._Poiteau._--_Paris_Henri_Plon,_Editeur,_1872.jpg) looks nice, too…

**Comment by westnordost** [comment]
Would probably work as well, though it should be consistent: Either all images use illustrations like this or none. And I doubt that there are illustrations like this for every crop.

**Comment by rugk** [comment]
Yeah, so I am currently using photos.
