### ISSUE TITLE
Some nice images by fir0002 have license problems

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#22]
https://commons.wikimedia.org/wiki/File:Pair_of_lemons.jpg and https://commons.wikimedia.org/wiki/File:Lemon_closeup.jpg have license problems. 

License: CC BY-NC or GFDL 1.2 or GFDL v1.2

If I understand it correctly also Wikipedia/Wikicommons does not allow NC, so they seem to use GFDL v1.2 and do that crazy attribution required there. You can also mail the author to negotiate a different license…

These images are very yellow :smile: :lemon:, but I'll add another not-so-nice, but acceptable photo for now.

**Comment by rugk** [comment]
Same: grape, https://commons.wikimedia.org/wiki/File:Grapes.jpg

**Comment by westnordost** [comment]
Yeah, too bad. GFDL is not compatible with GPL either. One could always ask the author, as hinted in that description.

**Comment by rugk** [comment]
Yeah, maybe drop him a mail. 

Another one: plums, https://commons.wikimedia.org/wiki/File:Plum_on_tree.jpg

The pics are really nice and he seems to make many…

**Comment by westnordost** [comment]
Ah, same guy. Though for plums, I would say the photo makes them seem as large as apples.

**Comment by rugk** [comment]
For plumps I found another nice one. Soon uploaded…

**Comment by rugk** [comment]
I am closing this, we found other nice images instead…
