### ISSUE TITLE
Lime

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#23]
Free lime pics are quite rare as I see. I've included a nice one, but maybe you like a differet one better:

* ![](https://upload.wikimedia.org/wikipedia/commons/d/d3/Citrus_%C3%97aurantiifolia927505341.jpg) https://commons.wikimedia.org/wiki/File:Citrus_%C3%97aurantiifolia927505341.jpg
* ![](https://c4.staticflickr.com/4/3415/3429288289_4c5399d720_o.jpg) https://www.flickr.com/photos/pfibiger/3429288289
* **included:** ![](https://c7.staticflickr.com/5/4078/4918425731_aa296af031_o.jpg) https://www.flickr.com/photos/tanaka_juuyoh/4918425731

Note: Flickr does not seem to like hotlinking… somehow it does not load here, but you have the link.

**Comment by westnordost** [comment]
Best would be a picture where both the fruit and the leaves are visible. That would be the second one. Though unfortunately, the fruit is blurred there, so I guess the first is better.

**Comment by rugk** [comment]
Hmm, and you really don't like the current one? From a stylistic perspective it's nice, but leafs are not really visible…

**Comment by westnordost** [comment]
It's fine too. I saw the issues before I saw the committed stuff

**Comment by rugk** [comment]
(I've linked it in the issue there too…)

So final question: Is the current one okay or should I replace it with one where leaves are visible… (Maybe on of the other ones proposed here?)

**Comment by westnordost** [comment]
The one now is fine too.
