### ISSUE TITLE
Mango

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#24]
The thing is that they can have many many colors. In small sizes they may look like cherries or limes or so…

I've included a picture for now, but it's green and not so nice.

Research needed: https://ccsearch.creativecommons.org/?search=mango&page=1&licenses=ALL-%24&licenses=ALL-MOD&search_fields=title&search_fields=creator&search_fields=tags&per_page=50&work_types=photos&providers=500px&providers=flickr

**Comment by westnordost** [comment]
Regarding the color, mangos are like apples, they come in green, red and both. I'd search for "both", i.e. the color: https://ccsearch.creativecommons.org/image/detail/0Kl0OFVdNborPAqIeJwFDA== (but should be on a tree)

**Comment by rugk** [comment]
From https://github.com/rugk/crops-parser/commit/f94e80016b65892061e226e3c2c2bf3c07eacd12:
> mango: perhaps it should be visible more from the tree? I wouldn't have guessed it is a mango

**Comment by rugk** [comment]
> I'd search for "both", i.e. the color: https://ccsearch.creativecommons.org/image/detail/0Kl0OFVdNborPAqIeJwFDA== 

Ooh, hard requirement, but I'll look…

**Comment by rugk** [comment]
Really hard I could not find any pictures meeting your criteria. I found [this](https://commons.wikimedia.org/wiki/File:Mangos_Bajitos.JPG), but it may not be a real mango (not mago indica; they are also somewhat smaller) and [this](https://commons.wikimedia.org/wiki/File:MangotreeindialanticFL.jpg), but this looks strange. 

[This](https://commons.wikimedia.org/wiki/File:Mangue_d%27Ampiraboka.jpg) somewhat looks good, but it is 90% yellow 10% red. ([Here we have a red version](https://commons.wikimedia.org/wiki/File:Mangue_d%27Andampy.jpg))

I've looked through Wikicommons and CCSearch until page 9.

Maybe the issue is also just that change the colour when they are not at the tree anymore, so they are harvested in a particular state. Don't know though…

**Comment by rugk** [comment]
@westnordost This is the last image about one particular picture…

**Comment by westnordost** [comment]
I found this one: https://pixabay.com/de/mango-mangifera-indica-%C3%BCber-reif-321071/

Though, not particularly better, so this can be closed.
