### ISSUE TITLE
Coconut

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#25]
Needs review as you mostly only find pictures of them when they are not on the tree anymore. And they are yellow on a tree, BTW. But maybe that picture even helps to find them.

**Comment by westnordost** [comment]
Simply search for "coconut tree", not "coconut".

**Comment by rugk** [comment]
From https://github.com/rugk/crops-parser/commit/f94e80016b65892061e226e3c2c2bf3c07eacd12:
> coconut: I think this is a rather untypical picture. All the coconuts I have seen were greenish. Also, perhaps a picture where a little more of the tree is visible because the tree itself is quite characteristic?

**Comment by rugk** [comment]
I think the issue for including a tree is that it is too small. When you try to put a coconut tree in this small square picture this will not really work. And you cannot see the coconut itself, then…

Maybe they are not yet ripe when yellow. In any case yellow is a better contrast to the green leaves. I don't like green fruits because of this.

**Comment by westnordost** [comment]
IU was thinking something like this:

https://ccsearch.creativecommons.org/image/detail/86vQle7Q14CvD7dGjm1vuw==

**Comment by rugk** [comment]
Yeah, thanks nice pic. I added it!
