### ISSUE TITLE
Grapes

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#26]
I've added two versions? grape1 or grape2? The second one is a bit dark, but has a nice form, the first one is light, but looks like a big pile…

**Comment by rugk** [comment]
@westnordost So? 1 or 2?

**Comment by westnordost** [comment]
2 is too dark even though the shape is more typical, so 1.

**Comment by rugk** [comment]
Maybe also replace it with https://pixabay.com/de/weintrauben-wein-traube-blau-blatt-1730723/ or https://pixabay.com/de/weintrauben-rotwein-weinberg-1717387/?

**Comment by westnordost** [comment]
Shape looks more typical, yeah

Am 24. Juli 2017 14:27:35 MESZ schrieb rugk <notifications@github.com>:
>Reopened #26.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crops-parser/issues/26#event-1176006897

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
