### ISSUE TITLE
Cherries

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#28]
The current cherries have a quite an unusual color, darker ones would be better IMO

**Comment by rugk** [comment]
Okay, there are a [lot of pictures](https://commons.wikimedia.org/wiki/Category:Cherries). Choose a nice one.

**Comment by westnordost** [comment]
I choose you! https://commons.wikimedia.org/wiki/File:2_cherries.jpg

**Comment by rugk** [comment]
Uuh, nice one. I'll add ~it~ you :cherries:  instantly!
