### ISSUE TITLE
Plum

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#29]
The photo makes the plum look very big. Perhaps instead use a photo with multiple plums inside.

Like this
https://ccsearch.creativecommons.org/image/detail/nWyvirHPWEVR9GqreIcCeA==
or this
https://ccsearch.creativecommons.org/image/detail/Sh6yfU3mEwW96lIMc5uxkQ==
(cropped of course)

**Comment by rugk** [comment]
Okay, I've used another photo, however.
