### ISSUE TITLE
Coffee?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#3]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Caturra_amarillo.JPG/576px-Caturra_amarillo.JPG?uselang=de)

It's a shrub, so should we include it?

**Comment by westnordost** [comment]
[Looks very plantationy to me](https://duckduckgo.com/?q=coffee+plantation&t=ffsb&iax=1&ia=images)

**Comment by rugk** [comment]
Okay, what about growing, then?

* [x] is perennial/always grown in monoculture
* [x] is grown on orchards/satellite images can be confused with orchards

**Comment by westnordost** [comment]
As far as I know, it is grown perennial/monoculture.

**Comment by rugk** [comment]
done
