### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#32]
I like the current raspberry pic, because you can see the leaves, but [this one](https://commons.wikimedia.org/wiki/File:Framboise_Margy_3.jpg) looks really great, promising and is a good photo. (On Wikicommons it's also a "quality image".)

So leave or change it? Or maybe yet another photo?

**Comment by rugk** [comment]
Okay, I found better ones (and another free image platform to bring some diversity in here :wink:). Choose the one you like:
* interesting, because with a transparent background – is that okay? https://pixabay.com/de/himbeere-obst-rot-539144/
* https://pixabay.com/de/obst-himbeeren-garten-2292701/
* https://pixabay.com/de/beeren-von-einer-himbeere-1700485/
* https://pixabay.com/de/himbeere-frucht-natur-sommer-berry-852289/
* https://pixabay.com/de/himbeer-garten-garten-obst-lean-1520612/

**Comment by westnordost** [comment]
mmhh :-p

**Comment by rugk** [comment]
Yummy!…😛 ah… well… not… back to business… :smiley: Would transparent be okay theoretically, or does it look ugly?

**Comment by rugk** [comment]
BTW (I just noticed) all pictures with German titles (as opposed to my search), so potentially all German raspberries/photographers (never imagined I would use these two words with an "or" conjunction respectively slash together…). And they are certainly not translated.

**Comment by westnordost** [comment]
I think transparent does not fit to the other stuff.

**Comment by rugk** [comment]
Please choose an image.

**Comment by westnordost** [comment]
2
