### ISSUE TITLE
Rubber alternatives

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#33]
As for the rubber tree, I, of course, not choose an image showing the fruits, but the tapped tree showing the rubber…

However, one may also like to see the tree as it is likely not harvested at any time and one should recognize the tree without the rubber.

So do you like the image I choose (soon uploaded)? If not, here are nice alternatives:
* https://commons.wikimedia.org/wiki/File:Pokok_Getah.jpg
* https://commons.wikimedia.org/wiki/File:NP_Llanos63_lo_(5853947184).jpg
* https://commons.wikimedia.org/wiki/File:Latex_-_Hevea_-_Cameroun.JPG
* (just FYI, this is currently used:) https://pixabay.com/de/harz-harzgewinnung-baum-baumrinde-2290750/

@westnordost

**Comment by westnordost** [comment]
I find the https://commons.wikimedia.org/wiki/File:Latex_-_Hevea_-_Cameroun.JPG best
