### ISSUE TITLE
Hazel nut

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#34]
As the hazel nut looks quite different when at the tree as a fruit and later freed, etc. I've included a collage version `hanzel_with_nut.jpg` (and source `.xcf` for further editing).

May we use this picture? @westnordost

![](https://raw.githubusercontent.com/rugk/crops-parser/cb2958c84113e7e1815824294756db168642a4b7/images/hazel_with_nut.jpg)

**Comment by westnordost** [comment]
I'd say, leave it out, this is not needed and may even confuse. We don't have the same for coconuts either.

The picture serves the user to recognize a fruit on the tree, he doesn't need to know how it looks later. Don't forget that at the bottom of each image, there will be the name of the fruit - so if the user comes by an orchard that grows hazelnut and there is a sign saying that it is growing hazelnut or whatever, he can select it by the name.

**Comment by rugk** [comment]
Okay, I've removed it.
