### ISSUE TITLE
Batch processing for images

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#35]
@westnordost 

In which size do we need these images? I saw we need an HDPI version and a low one…
(In case we later need to restore the image, it is in the git history of this repo :smiley:)

Also I'd pass them through https://tinyjpg.com/, so we can save much space.

**Comment by westnordost** [comment]
Do you think the photos can be displayed in three columns just like the street surfaces? Then it is for xxhdpi 384x384. The ones for lower dpi I can create myself during import.

Am 24. Juli 2017 16:29:39 MESZ schrieb rugk <notifications@github.com>:
>@westnordost 
>
>Which size do we need these images? I saw we need an HDPI version and a
>low one…
>(In case we later need to restore the image, it is in the git history
>of this repo :smiley:)
>
>Also I'd pass them through https://tinyjpg.com/, so we can save much
>space.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crops-parser/issues/35

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> Do you think the photos can be displayed in three columns just like the street surfaces? 

Yeah, think so.

> Then it is for xxhdpi 384x384.

Okay, I'll do that once all other issues regarding the images are closed.

**Comment by rugk** [comment]
For ref: Using GNOME Files.
