### ISSUE TITLE
trees=*_plants vs crop=*

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#36]
In the csv, it is simply crop=vanilla. If it is grown on an orchard, and it seems that it is, `trees=vanilla_plants` should be ok as well, as for all the other values.

**Comment by rugk** [comment]
I have no idea what is preferred. You can use both versions with any fruit/thing in the list. When we did https://github.com/rugk/crops-parser/issues/15, we decided for that one. In the review process nobody complaint (no one from the OSM mappers in the wiki), it is now listed in the wiki… I rather not want to change it now…

**Comment by westnordost** [comment]
Well, I "must" use what is [in here](https://github.com/rugk/crops-parser/blob/master/result/mostPlantedCrops_2014%2B2013_OSMonly.yml) because it makes no sense if I manually edit this file after the automic generation.

**Comment by rugk** [comment]
Yes, and I can certainly change that… I don't care how it is tagged, I rather want to tag it (correctly) at all… but OSM has no ~real~ policy what to prefer in those cases.

**Comment by westnordost** [comment]
Personally I prefer crop or produce for everything, but it seems that trees kinda established themselves (for orchard, and crop for farmland). So, in my opinion, then this tag should also be consistently used for orchard.

**Comment by rugk** [comment]
Is it really worth to change it now? (Make a PR… :wink: ) I mean I would at least like to add it to the wiki page, again, prior to using it "in production"…

**Comment by westnordost** [comment]
There is no rush. The "add orchard produce" will not find its way into a v1 release anyway because it takes some time for the translators to pick up on the new strings. (v1 is more or less in a feature-freeze now).

**Comment by rugk** [comment]
I think the strings were translated quite quickly as we saw. But yeah, if it is feature-frozen, does not matter.

**Comment by westnordost** [comment]
Only for German

On July 27, 2017 12:35:43 PM GMT+02:00, rugk <notifications@github.com> wrote:
>I think the strings were translated quite quickly as we saw. But yeah,
>if it is feature-frozen, does not matter.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crops-parser/issues/36#issuecomment-318325322

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Spanish was also quite fast.

Anyway, back to topic: Which OSM tags do you want to change? I can also give you push access, if that helps.

BTW You can also watch this repo, so I do not always have to mentioned you in new issues. :smile:

**Comment by westnordost** [comment]
I started a thread in the [tagging mailing list](https://lists.openstreetmap.org/pipermail/tagging/2017-July/032922.html), let's see what is the general opinion.

**Comment by westnordost** [comment]
Okay, so what I took out of this discussion is to use produce for everything, as trees should only be used for a subset of the possible values (i.e. trees=apple_trees but not anything not-tree) while produce can be used for any produce-value.
Also, there are different opinions on how much the orchard landuse still encompasses, one opinion is that it should only include tree-things. But either way, this does not really touch this quest type because we will simply not re-tag an orchard/farmland to something else but just add the produce.

PR incoming...

**Comment by westnordost** [comment]
Hm, I am unable to clone this repository somehow, ... perhaps bad internet connection(?)

I'll simply add the new CSV here:

[crops.txt](https://github.com/rugk/crops-parser/files/1191822/crops.txt)

I kept tree-taggings in a separate columns for reference and removed produce= because it is clear that it is always the same key.

**Comment by rugk** [comment]
The repo is quite big thanks to the image files… :laughing: 

So could you try again? A PR is much better to review… Otherwise I'll just create a PR myself and have a look on it.
(Hopefully you used LibreOffice Calc or so, as your file was not named .csv – which can be opened with Calc)

Also what should the script use to output. The "produce" value?

**Comment by westnordost** [comment]
Yes, that would be nice.
Yes.
Yes, the second column.

**Comment by rugk** [comment]
The PR is not merged yet, but ok. I'll change the nuts thing afterwards, BTW. (Or make a new PR.)
