### ISSUE TITLE
Strawberries tag

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#37]
Why are strawberries in the list? Is this a mistake?

Also, in the list they are mentioned as `crop=strawberry` but all the other berries are mentioned like i.e. `trees=raspberry`, that looks like a mistake.

**Comment by westnordost** [comment]
I mean, should it be crop=raspberry or trees=raspberry? If the latter, I would expect something like trees=raspberry_plants

**Comment by rugk** [comment]
They are berries (not in a biological sense, but for common sense), so https://github.com/rugk/crops-parser/issues/5
(Even opened another issue for them as I first forgot them: https://github.com/rugk/crops-parser/issues/19)

"fruit garden", you know…

For the other question, again: https://github.com/rugk/crops-parser/issues/15#issuecomment-313793810
Complain somewhere else… :wink:
