### ISSUE TITLE
Nuts & palms

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#39]
I think these two should be excluded as well because they are too generic. Especially "palms", what does this even mean?
Regarding nuts, the main difficulty is that the image shows the processed nuts, so how would a surveyor know that any kind of plantation is a plantation that grows nuts (but none of the other ones)? For other values, there are no category-answers like "fruits", "berries" etc., so "nuts" feels out of place, imo.

**Comment by rugk** [comment]
Palms are mentioned in the source data [as "palm kernels"](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv#L43). Maybe, however, the kernels from oil palms are also reused or so…
Thing is, maybe users cannot decide between palms and oil palms, but at least tagging things as palms would already help… (Could also be a category as in the street surface quest)

> Regarding nuts, the main difficulty is that the image shows the processed nuts,

It does not. I always selected images, where the fruit is hanging on a tree.

Ah you mean "nuts.jpg", well, right. 
The nut category actually includes different nuts as you can see in the [OSM conversion list](https://github.com/rugk/crops-parser/blob/master/osmcrops.csv#L11) (search for nuts).
Tung nuts, Areca nuts, Brazil nuts…
We could, of course, make a tag for each of them. (as it is with walnuts, etc.) Just wonder whether the user can decide between these… :thinking:

**Comment by westnordost** [comment]
I don't know what palm kernels are, so I had a look in the wikipedia: https://en.wikipedia.org/wiki/Palm_kernel

Seems to be oil_palms?

Well I would say that something is a palm could already be determined from aerial, no? Not sure how it would help to tag something just as "palm". I wouldn't tag something as "bush" or "tree" either.

> nuts

The user can always leave a note, describing what else is being cultivated there which is not in the list (if he knows).

**Comment by rugk** [comment]
About palms…

Hmm, the thing is the source data has all tree:
* Oil, palm
* Oil, palm fruit
* Palm kernels

In the OSM file you can see how they are mapped to OSM tags…

So I think "palm kernels" may be just the "palm kernel cake". And it could certainly be that it is only  a "side product" of the palm oil production, i.e. the plants/fields/explanations/orchards are all the same. Don't know though…
If so, I would rather remove "palm" from the list , or, better, just add it to "oil palm"…

> I wouldn't tag something as "bush" or "tree" either.

Yeah, good argument, but not that correct as "palm" is a real [biological familiy](https://en.wikipedia.org/wiki/Arecaceae) (i.e. it not only describes the form, how a plant grows; also note the German name "Palmgewächse"). And "oil palm" also does refer to [different palms](https://en.wikipedia.org/wiki/List_of_plants_known_as_oil_palm).

> Well I would say that something is a palm could already be determined from aerial, no?

If the tagger did so… That's not a thing we should care about.

**Comment by rugk** [comment]
As for nuts…

Yes, of course a note is possible. The thing is just that all these nuts summed together are, in some countries, a mayor production. E.g in  BT they are the 2nd most produced crop in our list. (2013+2014 data) Only several places afterwards nutmeg and walnuts follow.
So maybe these nuts seem exotic for us, but in other countries they are very common…

This would, however, be an argument for adding a tag for each nut type. It does likely not help very much to tag an orchard as "nuts are grown here". So, yeah, which nuts?
This would, naturally, change the data again (and not all nuts would have to be in the top-15 at all), but if that's necessary…

I only not included walnuts etc in the "nuts" category as OSM already had tags for them… (But they also had this unspecific "nuts" tag in their wiki.)

**Comment by westnordost** [comment]
Hm okay, we can keep nuts then and make palm -> oi_palm.

**Comment by rugk** [comment]
You really want to keep nuts in such an unspecific "nuts" way? I mean for us these cover exotic nuts anyway (which are not displayed on the according image… :laughing:), and may only affect some countries anyway, but huh… Maybe until a user complains… :wink: 

As for palms, I am changing it.

**Comment by westnordost** [comment]
Complaint Driven Software Development ;-)

**Comment by rugk** [comment]
Is not this as every software is made? :stuck_out_tongue_winking_eye:

**Comment by rugk** [comment]
No, the nuts issue (no joke intended) is still an open question. We only solved the palms thing, but what is the decision for nuts?

**Comment by westnordost** [comment]
I understood 

> but huh… Maybe until a user complains… 😉

as "we leave it like it is now for now".

**Comment by rugk** [comment]
Is that the solution or do you want individual keys for each nut type? I mean if one thing is tagged as "nut" it likely won't be revisited by mappers (at least by ones using StreetComplete), so if we leave it we may introduce "unclear" data. If this guilt is okay for you… 🤓

**Comment by westnordost** [comment]
Hmm :-(...  I know, it's called StreetComplete, right? 

Ok, please name the nuts in the csv like tgey are named and not simply nuts. This way, they can be included also later in StreetComplete 

On August 1, 2017 11:49:51 PM GMT+02:00, rugk <notifications@github.com> wrote:
>Is that the solution or do you want individual keys for each nut type?
>I mean if one thing is tagged as "nut" it likely won't be revisited by
>mappers (at least by ones using StreetComplete), so if we leave it we
>may introduce "unclear" data. If this guilt is okay for you… 🤓
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crops-parser/issues/39#issuecomment-319507302

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
