### ISSUE TITLE
Sugar cane?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#4]
@westnordost
I excluded sugar beets (certainly not on orchards), but what about sugar cane? Could it be confused with trees/bushes, unlikey?

In https://github.com/rugk/crops-parser/issues/2#issuecomment-312483794 you were for including it, but we sugar cane fields are unlikely to be recognized as orchards from satellite images, right?

**Comment by westnordost** [comment]
Right

**Comment by rugk** [comment]
* [ ] is perennial/always grown in monoculture
* [ ] is grown on orchards/satellite images can be confused with orchards

> Normalerweise wird Zuckerrohr einjährig kultiviert. Mitunter wird die Zuckerrohrkultur mehrmals genutzt, kann aber maximal auf drei Ernten ausgedehnt werden und das auch nur bei ausreichend Düngung und Pflege.

https://www.klett.de/alias/1010384

So, exclude?

**Comment by westnordost** [comment]
Yes

**Comment by rugk** [comment]
done in next commit
