### ISSUE TITLE
Remove Jute

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#40]
In my opinion, Jute should not be in that list. It is harvested fully, it is not perennial and it does not look like an orchard from aerial pictures. (Curiously, a lot of sisal plantation are shown if you search images for "jute plantation").

**Comment by rugk** [comment]
Note: I already had the note "only grows for one year" in my comments in the OSM file, so… :laughing: 
But there was indeed no discussion before, but yeah, they are likely not confused with orchards.
