### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#42]
So for a few countries, there are very few, sometimes only one, entries in the [mostPlantedCrops_2014%2B2013_OSMonly.yml](https://github.com/rugk/crops-parser/blob/master/result/mostPlantedCrops_2014%2B2013_OSMonly.yml) which is a problem because then for i.e. **Vietnam, you'd have only one choice - bananas**. Obviously the FAO data is not complete, so there must be some kind of fallback.

Do you have ideas?

Solutions come to my mind:
* don't show the quest at all for countries with less then 3 choices. More a workaround than a solution
* have the "show more" button show **all** defined fruits -  this is... not so good because most are irrelevant for any given location
* sort entries by climate zones, have a dictionary (country -> climate zones) and do the same as above
* manually research at least for the countries that have too few choices what else would grow there / what else is being known for growing there

**Comment by rugk** [comment]
Maybe just have an entry "default" (which I had previously), which is used to fill-up the list to 15 items when there are too few ones… It should just reflect the global "top-15" list.
Well… maybe there are countries where not many different fruits are planted. :smile: 

> climate zones, have a dictionary

Thing is, we do not have this.

**Comment by rugk** [comment]
Note that we also have some countries (e.g. Western Sahara) where we have no data at all… I mean you are also unlikely to find an "orchard" in the Western Sahara, but you should at least have the possibility to mark it as "nonexistent" or so… So I think showing some default fruits there would not hurt.

Another idea would be to use the data from countries "near" the current country for filling the list. That could get more useful/accurate data than just using the default. However, I think, that's quite difficult to implement.

**Comment by rugk** [comment]
I think this is not the only quest where data is missing for some countries, so how do you handle this case in the other quests? Use some default?

**Comment by westnordost** [comment]
For sports, there is indeed a default order and the country specific info is just used to reorder the list (not to exclude allothers)

On July 27, 2017 1:12:47 PM GMT+02:00, rugk <notifications@github.com> wrote:
>I think this is not the only quest where data is missing for some
>countries, so how do you handle this case in the other quests? Use some
>default?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rugk/crops-parser/issues/42#issuecomment-318332776

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
(By the way I did a little research out of interest and found that at least jackfruit and pineapples are produced in Vietnam.)

**Comment by rugk** [comment]
AFAIK jackfruit are not included in our (OSM tags) list currently.

**Comment by westnordost** [comment]
I'll go with 

> have the "show more" button show all defined fruits - this is... not so good because most are irrelevant for any given location

Not too nice, but we put too much work into this quest already.
