### ISSUE TITLE
Oil palms in iceland – zero values in result

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#43]
[Huh??](https://github.com/rugk/crops-parser/blob/master/result/mostPlantedCrops_2014%2B2013_OSMonly.yml#L92)

**Comment by rugk** [comment]
Haha :laughing: that's interesting. 
Indeed in the source data the value is set to "0" (No idea, why they include it…), but it seems to be the only value that goes through our filtering.

Element | Item Code | Item | Year Code | Year | Unit | Value
-- | -- | -- | -- | -- | -- | --
Production | 558 | Berries nes | 2013 | 2013 | tonnes | 24
Production | 558 | Berries nes | 2014 | 2014 | tonnes | 24
Production | 358 | Cabbages and other brassicas | 2013 | 2013 | tonnes | 234
Production | 358 | Cabbages and other brassicas | 2014 | 2014 | tonnes | 269
Production | 426 | Carrots and turnips | 2013 | 2013 | tonnes | 360
Production | 426 | Carrots and turnips | 2014 | 2014 | tonnes | 494
Production | 393 | Cauliflowers and broccoli | 2013 | 2013 | tonnes | 51
Production | 393 | Cauliflowers and broccoli | 2014 | 2014 | tonnes | 44
Production | 397 | Cucumbers and gherkins | 2013 | 2013 | tonnes | 1781
Production | 397 | Cucumbers and gherkins | 2014 | 2014 | tonnes | 1807
Production | 449 | Mushrooms and truffles | 2013 | 2013 | tonnes | 585
Production | 449 | Mushrooms and truffles | 2014 | 2014 | tonnes | 596
Production | 257 | Oil, palm | 2013 | 2013 | tonnes | 0
Production | 257 | Oil, palm | 2014 | 2014 | tonnes | 0
Production | 116 | Potatoes | 2013 | 2013 | tonnes | 6000
Production | 116 | Potatoes | 2014 | 2014 | tonnes | 8300
Production | 388 | Tomatoes | 2013 | 2013 | tonnes | 1560
Production | 388 | Tomatoes | 2014 | 2014 | tonnes | 1516

We seem to exclude tomatoes ([Why?](https://github.com/rugk/crops-parser/issues/44)), mushrooms and things like that and berries as this is too unspecific.

**Comment by rugk** [comment]
So now I exclude "0" as a value and iceland has no data anymore.
