### ISSUE TITLE
Tomatoes?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#44]
Currently excluded, wonder why… usually picked up.

* [x] is perennial/always grown in monoculture (mostly greenhouses)
* [x] is grown on orchards/fruit gardens/satellite images can be confused with orchards

**Comment by westnordost** [comment]
Hmm no idea. Perhaps because it is often grown in greenhouse-horticultures instead of on orchard? But that is not really an argument.

**Comment by rugk** [comment]
No that would be a good argument for including them. Because in these greenhouses they certainly do not do crop rotation or so… :smile: 

So I think we should include them again…

**Comment by rugk** [comment]
BTW as for "horticultures". Tomatoes are also often in "fruit gardens"… This definition of "orchard" by also including "fruit gardens" is a bit annoying…
