### ISSUE TITLE
Beginner's pull request

### ISSUE THREAD

**Issue by cyanate** [rugk/crops-parser#46]
I can't figure out how to actually send my changes from the commandline to this repo.

These are my changes:

[osmcrops.csv](https://github.com/rugk/crops-parser/files/1198236/osmcrops.txt)
[area_harvested_2014.csv](https://github.com/rugk/crops-parser/files/1198239/area_harvested_2014.txt)

**Comment by rugk** [comment]
Better try to learn it, it will be useful later… Fork this repo, clone it locally, make the changes and upload (push) them again. Then you can make the PR online. If these terms just confuse you, have a look [at this guide e.g.](https://guides.github.com/introduction/flow/). There is also a GUI from GitHub which simplifies the task, e.g.

**Comment by rugk** [comment]
Ah, now I found the correct help article: https://help.github.com/articles/github-flow/

**Comment by cyanate** [comment]
@rugk Ok, I've learned it (from commandline): https://github.com/rugk/crops-parser/pull/47
But I've got some encoding problems - are you or am I not using utf-8?

**Comment by rugk** [comment]
Basically:

```shell
git add . # add all changes to staging
git commit # commit staged changes, asks for commit message etc.
git push # upload changes
```

**Comment by rugk** [comment]
I use UTF-8.
![grafik](https://user-images.githubusercontent.com/11966684/28995995-659b8f38-79f7-11e7-8601-23d8d72ff0b3.png)

I also added the editorconfig file so you can use [addons for most editors](http://editorconfig.org/#download) and things like encoding and line ending should be handled automatically.
