### ISSUE TITLE
'NO'

### ISSUE THREAD

**Issue by westnordost** [rugk/crops-parser#48]
Because YAML is weird, you need to put 'NO' (Norway) in '' in the output.

**Comment by rugk** [comment]
Hell, that is strange. Because I am curious: Any explanation why? (i.e. a link?)

**Comment by westnordost** [comment]
Yaml parsers are so "smart" to interpret `yes, no, YES, NO, false, FALSE, true, TRUE` as booleans, even if it is a key in a map.
This "feature" has been removed in the newest version of the YAML standard, but few/no libraries actually use the newest standard.

**Comment by rugk** [comment]
Oh dear… Thanks for the explanation though.

**Comment by rugk** [comment]
For later reference btw: https://noyaml.com/ :upside_down_face: :sweat_smile:
