### ISSUE TITLE
Image for brazil nut

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#49]
(German: Paranuss)

I could not find one, which satisfies our requirements.

Pictures are really rare.
* https://commons.wikimedia.org/wiki/Bertholletia_excelsa, no whole fruit on tree
* pixabay nothing
* https://ccsearch.creativecommons.org/?search=brazil+nuts&page=1&licenses=ALL-%24&licenses=ALL-MOD&search_fields=title&search_fields=creator&search_fields=tags&per_page=50&work_types=photos&providers=500px&providers=flickr, only one site, not suitable

We could, however, use the bloom. There we have enough pictures.

**Comment by westnordost** [comment]
The bloom is fine

**Comment by westnordost** [comment]
Though, no need to find all the images now. They can be added later as well. I am eager to integrate the pictures we already have, because the basic quest is basically finished already (minus the pictures), but you said you wanted to batch-process all the images to the mentioned resolution first (which makes sense).

**Comment by rugk** [comment]
> you said you wanted to batch-process all the images to the mentioned resolution first (which makes sense).

And that's why I really wanted to have the pictures first. I am nearly finished, so…

**Comment by rugk** [comment]
I first wanted to use the image below then I noticed the Flickr [description](https://www.flickr.com/photos/mauroguanandi/3306955180) and the author obviously confused this with cashew nuts…

![3306955180_1d60853950_o](https://user-images.githubusercontent.com/11966684/29047342-a0ddf452-7bcb-11e7-80d8-62b460705449.jpg)

**Comment by rugk** [comment]
BTW one can find pictures of the same family, but I d not wish to use those. (e.g. https://www.flickr.com/photos/dinesh_valke/468588962)
