### ISSUE TITLE
Berries?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#5]
@westnordost

![grafik](https://user-images.githubusercontent.com/11966684/27824500-fd660fd2-60ac-11e7-854f-9bf5afa2b178.png)

Include or exclude them?

And [currants](https://en.wikipedia.org/wiki/Ribes)?

**Comment by westnordost** [comment]
I have never seen a berry plantation in real life. On image search, it looks perennial / shrubby.

**Comment by rugk** [comment]
I think they met the "fruit garden" thing, which is unfortunately also tagged as orchard.

* [x] is perennial/always grown in monoculture (unknown)
* [x] is grown on orchards/satellite images can be confused with orchards OR is gown in fruit gardens

**Comment by rugk** [comment]
Also adding Cranberries here.

**Comment by rugk** [comment]
done in next commit
