### ISSUE TITLE
Pepper, piper, what?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#50]
Cleaning up my confusion:

* Black pepper = [Schwarzer Pfeffer](https://de.wikipedia.org/wiki/Pfeffer) = Piper nigrum = piper.jpg
  Genus: Piper/Pepper; pepper family
*  [Paprika (inlc. chilli)](https://de.wikipedia.org/wiki/Paprika) = Capsicum = pepper.jpg is our chili image, the [Thai chili](https://en.wikipedia.org/wiki/Bird's_eye_chili) version
  Genus: Capsicum; nightshade family
   The **fruits** of this plant are called "sweet/hot/… pepper".

So these are two heavily different plants. See also [this](http://www.differencebetween.com/difference-between-pepper-and-vs-capsicum/) for a detailed explanation.
Quoting one Wiki article about Capsicum:
> The name "pepper" comes from the similarity of the flavor to black pepper, Piper nigrum, although there is no botanical relationship with it or with Sichuan pepper. 

Who has invented such a thing…? The German names are clearly easier. :smile: 

So that is, why the source data has one entry where they name it "piper" and the other "peppers".

And, we may want to differentiate between chilli :hot_pepper:  and "other" Capsicum such as paprika. At least we do not want to have all Capsicum fields marked as "chilli" fields. I think this is already satisfied as we split the data.

**Comment by rugk** [comment]
While writing this issue I got it, the commit should fix the data.

**Comment by rugk** [comment]
Looking for an image for Capsicum (will be labeled "pepper.jpg" in the image dir).

BTW, I see it coming that this will confuse any translator. Hopefully they do it right. Too bad, we cannot ad comments…

**Comment by rugk** [comment]
Okay, maybe this issue is not that easy to solve. As, of course, this applies to OSM and OSM tags and these are set by people (when not using StreetComplete). And these may confuse this thing.

So this is also an OSM issue. A good idea, IMHO, would be to use "produce=paprika" and name the plant "capsicum" in the tags (capsicum_plant). See the wiki article about when the term [paprika is used](https://en.wikipedia.org/wiki/Capsicum#Etymology_and_names):
> The fruit is called "paprika" in some other countries (although paprika can also refer to the powdered spice made from various capsicums).

However, "some countries" is also bad, so… :thinking: 

So I reopen this issue as it needs OSM discussion or research (what is commonly used – although that is not a sign that we should do it (potentially wrong) too). As for StreetComplete I consider this issue solved, unless we have to change the tag names, of course.

**Comment by westnordost** [comment]
I'd say these tags allow for the least amount of confusion:
```
produce=bell_pepper,
produce=pepper, 
produce=chili
```

**Comment by rugk** [comment]
It's only called bell pepper in some countries, AFAIK. In the US it is e.g. "sweet pepper".

**Comment by westnordost** [comment]
US doesn't matter, OSM uses British English.

**Comment by rugk** [comment]
Anyway to prevent confusion I would still prefer `produce=piper` (the scientific name) for black pepper as `produce=pepper` is maybe misinterpreted to mean bell peppers.

**Comment by westnordost** [comment]
Ok

**Comment by rugk** [comment]
As I said, this rather needs a bigger discussion or some "spec" or so… Usually this is the wiki, but here it is bad as we experienced.

So maybe starts another thread on the mailing list you once posted too, @westnordost?

**Comment by rugk** [comment]
TODO: https://github.com/westnordost/StreetComplete/commit/0a80c257b429c540ff6d82fdbeb76740d0da2a49

And next time, @westnordost, please comment here/let me know when you discuss such things (especially when I actually ask for it), please.
