### ISSUE TITLE
StreetComplete source data: tonnes or area?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#51]
@cyanate made me aware in https://github.com/rugk/crops-parser/pull/47 that we could also use the harvested area instead of tonnes as a source data. The script stays the same, only the result may naturally differ…

Just opening this opportunity. If you think we should switch, then we may switch and I'll look for missing pics for crops or so, in case this is needed.

**Comment by westnordost** [comment]
By area seems to make more sense as the area is really what matters for OSM. (Different crops need different areas for the same amount of crop in tonnes.)
So if the data quality is the same, by-area is better.

**Comment by westnordost** [comment]
Looking at Vietnam, which in the tonnes-dataset only has bananas, in the area-dataset, there is tea, rubber, pineapples, pepper, oranges, mangos, mangosteens, guavas, grapes, grapefruit, coffee, coconuts, chilis, cashew, bananas and more...

So it looks like this is even more complete.

**Comment by rugk** [comment]
Oh that's interesting. But I would rather avoid combining the data, as it is… well… how should these be combined?
So it seems you want to use area. Okay, we can do so (hope the crops do not change that much). We only have to merge https://github.com/rugk/crops-parser/pull/47 and then we have both data.
