### ISSUE TITLE
Add image author names to license file

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#53]
I admit I neglected to do it properly when collecting the images, but I should really go through the links and add the author names to the license file. For CC-BY(-…) licenses it is of course required and for all others I'll do it anyway.

**Comment by westnordost** [comment]
isn't it enough to add the link to the source? At the source, there will be the author information

**Comment by rugk** [comment]
It depends a bit on the used CC license (version). Seeing [the wiki](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution):
> These best practices are based on actual CC license requirements. Noting the title is a requirement of all CC licenses version 3.0 or earlier, optional for 4.0. Noting the author, source, license, and retaining any extra notices is a requirement of all CC licenses. See Devil in the details.

So for 4.0 you also need to mention the title, … well, that's maybe in the URL too. :wink:  

However, at least the [4.0 license](https://creativecommons.org/licenses/by/4.0/legalcode#s3a2) includes a "reasonable clause", so you may also just use the link depending on the medium. But to be safe…
The 1.0 and 2.0 license only allow this "reasonable" way "as at least as prominent as other authorship credit if an adaptation or collection". And that's the case here…

So, it's certainly your choice how to do it.

**Comment by westnordost** [comment]
Phew, didn't know that. What do you say, can I convince you to go through the authors.txt list in StreetComplete and complement what you think is legally required?

**Comment by rugk** [comment]
I'll go through my LICENSE.md here. (I think, I also change it to a table layout) You can then just copy it or so…
