### ISSUE TITLE
Duplicate entries & lines for South Sudan

### ISSUE THREAD

**Issue by sashazykov** [rugk/crops-parser#54]
https://github.com/rugk/crops-parser/blob/891c01cb05cdf85d005a2e77dca78f2b5dc7c088/result/mostTonnesHarvest_2014_OSMonly.yml#L180

https://github.com/rugk/crops-parser/blob/891c01cb05cdf85d005a2e77dca78f2b5dc7c088/result/mostTonnesHarvest_2014_OSMonly.yml#L181

There are two countries with SS code in the list and one of them has many duplicates (lemon, lime, etc)

**Comment by rugk** [comment]
Oh, you are right. That is interesting, specially as it is not even only in the combined "2013+2014" data set…

Let's tackle the duplicate lines problem, first. Maybe the other problem is also solved by it.

**Comment by rugk** [comment]
So in the ISO `South Sudan,SS,728` is only listed once…

And I also noticed my filter for "0 data" was not enough, because in South Sudan you actually cannot find lemons or limes. At least, there is no data…

**Comment by rugk** [comment]
Found the bug. It confused "Sudan" with "South Sudan". Will be fixed with next commit, just regenerating data…
