### ISSUE TITLE
New data 🎉

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#57]
Good news, here, @westnordost,
The UN does have [new data](http://www.fao.org/faostat/en/#data/QC) from up to 2017… :smile: 

So I've put them through my parser, also with two years averaged (2016+2017), and looked through the data a little and it seems to be all fine. (I just had to add `Eswatini` to the iso3166, which was previously referred to as "Swaziland", but well… that does not matter. :smile: 

So to me, it seems fine. Choose whatever resulting dataset you want. :smile:

**Comment by rugk** [comment]
Also re-generated the [list of missing/not-included OSM tags](https://github.com/rugk/crops-parser/blob/master/result/OsmOnly/missingOSM.list). (AFAIK that was the meaning of that data :laughing:)

**Comment by westnordost** [comment]
Feel free to create a PR with the updated data!

**Comment by rugk** [comment]
You first have to choose what date to use? Area, I guess? And 2016+2017 or only 2017?

2016+2017 could give a better average of the data, in case e.g. 2017 behaved differently than 2016.

I could likely also perfectly well choose an average of three years or so.

**Comment by westnordost** [comment]
Area, yes. I have no opinion on 2016/2017

Am 6. Januar 2019 11:44:28 MEZ schrieb rugk <notifications@github.com>:
>You first have to choose what date to use? Area, I guess? And 2016+2017
>or only 2017?
>
>2016+2017 could give a better average of the data, in case e.g. 2017
>behaved differently than 2016.
>
>I could likely also perfectly well choose an average of three years or
>so.
