### ISSUE TITLE
Beans?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#6]
@westnordost

![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/1403201213729_%D8%A7%D9%84%D8%AD%D9%88%D8%B6_%D8%A7%D9%84%D9%85%D8%A7%D8%A6%D9%8A.JPG/1024px-1403201213729_%D8%A7%D9%84%D8%AD%D9%88%D8%B6_%D8%A7%D9%84%D9%85%D8%A7%D8%A6%D9%8A.JPG)

![grafik](https://user-images.githubusercontent.com/11966684/27824699-9aee5818-60ad-11e7-8ea2-da1fa66c7307.png)

Grow on such fields… Possibly include them, right?

However, soybeans, are not that tall, so maybe exclude them?
![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/20110626Feld_Hockenheim5.jpg/640px-20110626Feld_Hockenheim5.jpg)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cambria%2C_Indiana.png/640px-Cambria%2C_Indiana.png)

**Comment by westnordost** [comment]
Hmm, looks more like farmland to me, all three and even up close. Also, beans (and other legumes) are a popular crop for intermediate plantation because they give the soil back some nutrients that cereals need. I would say, you'd never see a semi-permanent plantation of beans anywhere (for that reason).

**Comment by rugk** [comment]
* [ ] is perennial/always grown in monoculture (unknown)
* [ ] is grown on orchards/satellite images can be confused with orchards

Good arguments. Exclude.

**Comment by rugk** [comment]
Done in next commit. (Note that cacao beans are, of course, not affected. I'll leave them in there.)

So exclude: Soybeans and other beans like broad beans.
