### ISSUE TITLE
Peas?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#7]
@westnordost

Similar to beans https://github.com/rugk/crops-parser/issues/6, what about peas?

![grafik](https://user-images.githubusercontent.com/11966684/27824822-fe5b52b6-60ad-11e7-8006-f23576a3b817.png)

**Comment by westnordost** [comment]
Hmm, no idea. They are basically also legumes but seem to grow larger ( / are cultivated on sticks). Can't find any conclusive imagery or information whether they are planted in a semi-permanent fashion .

**Comment by rugk** [comment]
We need a decision here, yes or no…

Probably:
![](http://www.freshplaza.com/2016/0415/Lusciousfresh06.jpg)

**Comment by westnordost** [comment]
Well, I can't make that decision.

**Comment by rugk** [comment]
I'll say, exclude. Although grown on sticks they are quite small and rather fit into the "plantations" category.

* [ ] is perennial/always grown in monoculture (no idea??)
* [ ] is grown on orchards/satellite images can be confused with orchards
