### ISSUE TITLE
Peppers and chilies?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#8]
@westnordost

Exclude?

![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Cachi_02.jpg/640px-Cachi_02.jpg)

**Comment by westnordost** [comment]
I think the image shows chillies being left out to dry in the sun.
[Pepper plantation](https://duckduckgo.com/?q=pepper+plantation&t=ffsb&iax=1&ia=images) yields another image.
Can't say anything much about it anyway. Don't know if it is perennial or not.

**Comment by rugk** [comment]
I think perennial does not matter that much now.

Basically for inclusion two criteria have to be met:
* [x] is perennial/always grown in monoculture
* [x] is grown on orchards/satellite images can be confused with orchards

**Comment by westnordost** [comment]
Yes, include. The pictures speak for themselves. The plants are obviously grown on sticks for at least several years and the fruits are picked, not harvested.

**Comment by westnordost** [comment]
https://youtu.be/YccGzymacjw?t=65

This is chilli harvest btw, as opposed to i.e. hemp or potatoe harvest.

**Comment by rugk** [comment]
Nice, l very clearly orchard!
